import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google';
import "./globals.css";

import Script from "next/script";
import Providers from "./prodiver/providers";


const mainFont = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Gendragon",
  description: "Generated by Gendragon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
        <Script
          src="https://telegram.org/js/telegram-widget.js?22"
          strategy="afterInteractive"
          id="telegram-widget-script"
        />
      </head>
      <body
        className={`${mainFont.className}`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
