import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google';
import "./globals.css";

import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";


const mainFont = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.className}`}
      >
        <div className=" min-h-screen w-screen flex flex-col ">
          <Header />
          <div className="flex-1 bg-black bg-slate-200">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
